import type { Metadata } from "next";
import { Poppins, Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const poppinSans = Poppins({
  variable: "--font-poppins-sans",
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
});

const ralewaySans = Raleway({
  variable: "--font-raleway-sans",
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/icon.ico", sizes: "any", type: "image/x-icon" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinSans.variable} ${ralewaySans.variable} flex min-h-full flex-col bg-white`}
      >
        <Navbar />
        <main className="container grow mx-auto px-4 py-8">{children}</main>
      </body>
    </html>
  );
}
